const TelegramBot = require('node-telegram-bot-api');[span_0](start_span)[span_0](end_span)
const http = require('http');[span_1](start_span)[span_1](end_span)
const axios = require('axios');[span_2](start_span)[span_2](end_span)
const NodeCache = require('node-cache');[span_3](start_span)[span_3](end_span)
const crypto = require('crypto');[span_4](start_span)[span_4](end_span)

// Contact email included by the bot owner for source administrators.
const CONTACT_EMAIL = 'contact.docseeker@gmail.com';[span_5](start_span)[span_5](end_span)
const BOT_NAME = 'ResearchHelperBot';[span_6](start_span)[span_6](end_span)
const BOT_VERSION = '5.0';[span_7](start_span)[span_7](end_span)
const USER_AGENT = `${BOT_NAME}/${BOT_VERSION} (contact: ${CONTACT_EMAIL})`;[span_8](start_span)[span_8](end_span)

const TOKEN = process.env.BOT_TOKEN;[span_9](start_span)[span_9](end_span)
if (!TOKEN) {[span_10](start_span)[span_10](end_span)
  console.error('CRITICAL: BOT_TOKEN is missing in environment variables.');[span_11](start_span)[span_11](end_span)
  process.exit(1);[span_12](start_span)[span_12](end_span)
}[span_13](start_span)[span_13](end_span)

const bot = new TelegramBot(TOKEN, { polling: true });[span_14](start_span)[span_14](end_span)

// Query buttons expire after 60 minutes. No website is contacted when these are created.
const querySessionCache = new NodeCache({ stdTTL: 3600, checkperiod: 300 });[span_15](start_span)[span_15](end_span)
const wikipediaCache = new NodeCache({ stdTTL: 86400, checkperiod: 600 });[span_16](start_span)[span_16](end_span)
const arxivCache = new NodeCache({ stdTTL: 86400, checkperiod: 600 });[span_17](start_span)[span_17](end_span)
const pmcCache = new NodeCache({ stdTTL: 86400, checkperiod: 600 });[span_18](start_span)[span_18](end_span)
const wikipediaPdfCache = new NodeCache({ stdTTL: 3600, checkperiod: 300 });[span_19](start_span)[span_19](end_span)
const pmcPaperCache = new NodeCache({ stdTTL: 3600, checkperiod: 300 });[span_20](start_span)[span_20](end_span)
const inFlightCache = new NodeCache({ stdTTL: 300, checkperiod: 60, useClones: false });[span_21](start_span)[span_21](end_span)

const MAX_PDF_BYTES = 48 * 1024 * 1024;[span_22](start_span)[span_22](end_span)

function sleep(ms) {[span_23](start_span)[span_23](end_span)
  return new Promise((resolve) => setTimeout(resolve, ms));[span_24](start_span)[span_24](end_span)
}[span_25](start_span)[span_25](end_span)

function escapeHtml(value) {[span_26](start_span)[span_26](end_span)
  return String(value)[span_27](start_span)[span_27](end_span)
    .replace(/&/g, '&amp;')[span_28](start_span)[span_28](end_span)
    .replace(/</g, '&lt;')[span_29](start_span)[span_29](end_span)
    .replace(/>/g, '&gt;');[span_30](start_span)[span_30](end_span)
}[span_31](start_span)[span_31](end_span)

function decodeXml(value) {[span_32](start_span)[span_32](end_span)
  return String(value)[span_33](start_span)[span_33](end_span)
    .replace(/&lt;/g, '<')[span_34](start_span)[span_34](end_span)
    .replace(/&gt;/g, '>')[span_35](start_span)[span_35](end_span)
    .replace(/&quot;/g, '"')[span_36](start_span)[span_36](end_span)
    .replace(/&apos;/g, "'")[span_37](start_span)[span_37](end_span)
    .replace(/&amp;/g, '&');[span_38](start_span)[span_38](end_span)
}[span_39](start_span)[span_39](end_span)

function getXmlTagValue(xml, tagName) {[span_40](start_span)[span_40](end_span)
  const match = xml.match(new RegExp(`<${tagName}[^>]*>([\\s\\S]*?)<\\/${tagName}>`, 'i'));[span_41](start_span)[span_41](end_span)
  return match ? match[1] : '';[span_42](start_span)[span_42](end_span)
}[span_43](start_span)[span_43](end_span)

function makeFileName(title) {[span_44](start_span)[span_44](end_span)
  const cleanedTitle = String(title)[span_45](start_span)[span_45](end_span)
    .replace(/[\\/:*?"<>|]/g, '')[span_46](start_span)[span_46](end_span)
    .replace(/\s+/g, '_')[span_47](start_span)[span_47](end_span)
    .slice(0, 100);[span_48](start_span)[span_48](end_span)

  return `${cleanedTitle || 'research_document'}.pdf`;[span_49](start_span)[span_49](end_span)
}[span_50](start_span)[span_50](end_span)

function shortLabel(value, maxLength = 42) {[span_51](start_span)[span_51](end_span)
  const cleanValue = String(value).replace(/\s+/g, ' ').trim();[span_52](start_span)[span_52](end_span)
  return cleanValue.length > maxLength ? `${cleanValue.slice(0, maxLength - 1)}…` : cleanValue;[span_53](start_span)[span_53](end_span)
}[span_54](start_span)[span_54](end_span)

function normalizeQuery(query) {[span_55](start_span)[span_55](end_span)
  return String(query).trim().toLowerCase().replace(/\s+/g, ' ');[span_56](start_span)[span_56](end_span)
}[span_57](start_span)[span_57](end_span)

function getRequestConfig(extra = {}) {[span_58](start_span)[span_58](end_span)
  return {[span_59](start_span)[span_59](end_span)
    headers: {[span_60](start_span)[span_60](end_span)
      'User-Agent': USER_AGENT,[span_61](start_span)[span_61](end_span)
      ...(extra.headers || {})[span_62](start_span)[span_62](end_span)
    },[span_63](start_span)[span_63](end_span)
    timeout: 30000,[span_64](start_span)[span_64](end_span)
    ...extra[span_65](start_span)[span_65](end_span)
  };[span_66](start_span)[span_66](end_span)
}[span_67](start_span)[span_67](end_span)

function getRetryAfterMs(error, fallbackMs) {[span_68](start_span)[span_68](end_span)
  const retryAfter = error?.response?.headers?.['retry-after'];[span_69](start_span)[span_69](end_span)
  const seconds = Number(retryAfter);[span_70](start_span)[span_70](end_span)

  if (Number.isFinite(seconds) && seconds > 0) {[span_71](start_span)[span_71](end_span)
    return Math.min(seconds * 1000, 10 * 60 * 1000);[span_72](start_span)[span_72](end_span)
  }[span_73](start_span)[span_73](end_span)

  return fallbackMs;[span_74](start_span)[span_74](end_span)
}[span_75](start_span)[span_75](end_span)

function isRetryableError(error) {[span_76](start_span)[span_76](end_span)
  const status = error?.response?.status;[span_77](start_span)[span_77](end_span)
  return status === 429 || status === 503;[span_78](start_span)[span_78](end_span)
}[span_79](start_span)[span_79](end_span)

class SourceQueue {[span_80](start_span)[span_80](end_span)
  constructor(name, minimumIntervalMs) {[span_81](start_span)[span_81](end_span)
    this.name = name;[span_82](start_span)[span_82](end_span)
    this.minimumIntervalMs = minimumIntervalMs;[span_83](start_span)[span_83](end_span)
    this.pending = [];[span_84](start_span)[span_84](end_span)
    this.running = false;[span_85](start_span)[span_85](end_span)
    this.nextAllowedAt = 0;[span_86](start_span)[span_86](end_span)
  }[span_87](start_span)[span_87](end_span)

  setCooldown(milliseconds) {[span_88](start_span)[span_88](end_span)
    this.nextAllowedAt = Math.max(this.nextAllowedAt, Date.now() + milliseconds);[span_89](start_span)[span_89](end_span)
  }[span_90](start_span)[span_90](end_span)

  enqueue(task) {[span_91](start_span)[span_91](end_span)
    return new Promise((resolve, reject) => {[span_92](start_span)[span_92](end_span)
      this.pending.push({ task, resolve, reject });[span_93](start_span)[span_93](end_span)
      this.processNext();[span_94](start_span)[span_94](end_span)
    });[span_95](start_span)[span_95](end_span)
  }[span_96](start_span)[span_96](end_span)

  async processNext() {[span_97](start_span)[span_97](end_span)
    if (this.running || this.pending.length === 0) {[span_98](start_span)[span_98](end_span)
      return;[span_99](start_span)[span_99](end_span)
    }[span_100](start_span)[span_100](end_span)

    this.running = true;[span_101](start_span)[span_101](end_span)
    const item = this.pending.shift();[span_102](start_span)[span_102](end_span)
    const waitMs = Math.max(0, this.nextAllowedAt - Date.now());[span_103](start_span)[span_103](end_span)

    if (waitMs > 0) {[span_104](start_span)[span_104](end_span)
      await sleep(waitMs);[span_105](start_span)[span_105](end_span)
    }[span_106](start_span)[span_106](end_span)

    try {[span_107](start_span)[span_107](end_span)
      const result = await item.task();[span_108](start_span)[span_108](end_span)
      this.nextAllowedAt = Math.max(this.nextAllowedAt, Date.now() + this.minimumIntervalMs);[span_109](start_span)[span_109](end_span)
      item.resolve(result);[span_110](start_span)[span_110](end_span)
    } catch (error) {[span_111](start_span)[span_111](end_span)
      this.nextAllowedAt = Math.max(this.nextAllowedAt, Date.now() + this.minimumIntervalMs);[span_112](start_span)[span_112](end_span)
      item.reject(error);[span_113](start_span)[span_113](end_span)
    } finally {[span_114](start_span)[span_114](end_span)
      this.running = false;[span_115](start_span)[span_115](end_span)
      setImmediate(() => this.processNext());[span_116](start_span)[span_116](end_span)
    }[span_117](start_span)[span_117](end_span)
  }[span_118](start_span)[span_118](end_span)
}[span_119](start_span)[span_119](end_span)

const wikipediaQueue = new SourceQueue('Wikipedia', 1000);[span_120](start_span)[span_120](end_span)
const arxivQueue = new SourceQueue('arXiv', 4000);[span_121](start_span)[span_121](end_span)
const pmcQueue = new SourceQueue('PMC', 2000);[span_122](start_span)[span_122](end_span)

async function limitedGet(queue, url, config = {}) {[span_123](start_span)[span_123](end_span)
  return queue.enqueue(async () => {[span_124](start_span)[span_124](end_span)
    let lastError = null;[span_125](start_span)[span_125](end_span)

    for (let attempt = 0; attempt < 3; attempt += 1) {[span_126](start_span)[span_126](end_span)
      try {[span_127](start_span)[span_127](end_span)
        return await axios.get(url, getRequestConfig(config));[span_128](start_span)[span_128](end_span)
      } catch (error) {[span_129](start_span)[span_129](end_span)
        lastError = error;[span_130](start_span)[span_130](end_span)

        if (!isRetryableError(error) || attempt === 2) {[span_131](start_span)[span_131](end_span)
          throw error;[span_132](start_span)[span_132](end_span)
        }[span_133](start_span)[span_133](end_span)

        const fallbackDelay = 5000 * (2 ** attempt);[span_134](start_span)[span_134](end_span)
        const delayMs = getRetryAfterMs(error, fallbackDelay);[span_135](start_span)[span_135](end_span)
        queue.setCooldown(delayMs);[span_136](start_span)[span_136](end_span)
        await sleep(delayMs);[span_137](start_span)[span_137](end_span)
      }[span_138](start_span)[span_138](end_span)
    }[span_139](start_span)[span_139](end_span)

    throw lastError;[span_140](start_span)[span_140](end_span)
  });[span_141](start_span)[span_141](end_span)
}[span_142](start_span)[span_142](end_span)

async function runShared(key, work) {[span_143](start_span)[span_143](end_span)
  const active = inFlightCache.get(key);[span_144](start_span)[span_144](end_span)
  if (active) {[span_145](start_span)[span_145](end_span)
    return active;[span_146](start_span)[span_146](end_span)
  }[span_147](start_span)[span_147](end_span)

  const promise = work().finally(() => inFlightCache.del(key));[span_148](start_span)[span_148](end_span)
  inFlightCache.set(key, promise);[span_149](start_span)[span_149](end_span)
  return promise;[span_150](start_span)[span_150](end_span)
}[span_151](start_span)[span_151](end_span)

function createQuerySession(topic) {[span_152](start_span)[span_152](end_span)
  const token = crypto.randomBytes(12).toString('hex');[span_153](start_span)[span_153](end_span)
  querySessionCache.set(token, { topic: topic.trim() });[span_154](start_span)[span_154](end_span)
  return token;[span_155](start_span)[span_155](end_span)
}[span_156](start_span)[span_156](end_span)

function createGoogleSiteSearchUrl(domain, topic) {[span_157](start_span)[span_157](end_span)
  return `https://www.google.com/search?q=${encodeURIComponent(`site:${domain} ${topic}`)}`;[span_158](start_span)[span_158](end_span)
}[span_159](start_span)[span_159](end_span)

function createInternetArchiveSearchUrl(topic) {[span_160](start_span)[span_160](end_span)
  return `https://www.google.com/search?q=${encodeURIComponent(`site:archive.org/details ${topic}`)}`;[span_161](start_span)[span_161](end_span)
}[span_162](start_span)[span_162](end_span)

function createSourceButtons(topic, token) {[span_163](start_span)[span_163](end_span)
  return {[span_164](start_span)[span_164](end_span)
    inline_keyboard: [[span_165](start_span)[span_165](end_span)
      [[span_166](start_span)[span_166](end_span)
        { text: '📘 Wikipedia', callback_data: `src:wiki:${token}` },[span_167](start_span)[span_167](end_span)
        { text: '🔬 arXiv Research', callback_data: `src:arxiv:${token}` }[span_168](start_span)[span_168](end_span)
      ],[span_169](start_span)[span_169](end_span)
      [[span_170](start_span)[span_170](end_span)
        { text: '🩺 PMC Open Access', callback_data: `src:pmc:${token}` },[span_171](start_span)[span_171](end_span)
        { text: '📚 OAPEN Books', url: createGoogleSiteSearchUrl('library.oapen.org', topic) }[span_172](start_span)[span_172](end_span)
      ],[span_173](start_span)[span_173](end_span)
      [[span_174](start_span)[span_174](end_span)
        { text: '🎓 OpenStax Textbooks', url: createGoogleSiteSearchUrl('openstax.org', topic) },[span_175](start_span)[span_175](end_span)
        { text: '📖 Gutenberg Classics', url: createGoogleSiteSearchUrl('gutenberg.org', topic) }[span_176](start_span)[span_176](end_span)
      ],[span_177](start_span)[span_177](end_span)
      [[span_178](start_span)[span_178](end_span)
        { text: '🏛️ Internet Archive', url: createInternetArchiveSearchUrl(topic) },[span_179](start_span)[span_179](end_span)
        { text: '🔍 Dokumen.pub Search', url: createGoogleSiteSearchUrl('dokumen.pub', topic) }[span_180](start_span)[span_180](end_span)
      ][span_181](start_span)[span_181](end_span)
    ][span_182](start_span)[span_182](end_span)
  };[span_183](start_span)[span_183](end_span)
}[span_184](start_span)[span_184](end_span)

async function getWikipediaContent(query) {[span_185](start_span)[span_185](end_span)
  const normalized = normalizeQuery(query);[span_186](start_span)[span_186](end_span)
  const cacheKey = `wiki:${normalized}`;[span_187](start_span)[span_187](end_span)
  const cached = wikipediaCache.get(cacheKey);[span_188](start_span)[span_188](end_span)

  if (cached) {[span_189](start_span)[span_189](end_span)
    return cached;[span_190](start_span)[span_190](end_span)
  }[span_191](start_span)[span_191](end_span)

  return runShared(cacheKey, async () => {[span_192](start_span)[span_192](end_span)
    const cachedAfterWait = wikipediaCache.get(cacheKey);[span_193](start_span)[span_193](end_span)
    if (cachedAfterWait) {[span_194](start_span)[span_194](end_span)
      return cachedAfterWait;[span_195](start_span)[span_195](end_span)
    }[span_196](start_span)[span_196](end_span)

    const searchUrl = new URL('https://en.wikipedia.org/w/api.php');[span_197](start_span)[span_197](end_span)
    searchUrl.searchParams.set('action', 'query');[span_198](start_span)[span_198](end_span)
    searchUrl.searchParams.set('list', 'search');[span_199](start_span)[span_199](end_span)
    searchUrl.searchParams.set('srsearch', normalized);[span_200](start_span)[span_200](end_span)
    searchUrl.searchParams.set('srlimit', '1');[span_201](start_span)[span_201](end_span)
    searchUrl.searchParams.set('format', 'json');[span_202](start_span)[span_202](end_span)

    const searchResponse = await limitedGet(wikipediaQueue, searchUrl.toString());[span_203](start_span)[span_203](end_span)
    const searchResults = searchResponse.data?.query?.search;[span_204](start_span)[span_204](end_span)

    if (!searchResults || searchResults.length === 0) {[span_205](start_span)[span_205](end_span)
      return null;[span_206](start_span)[span_206](end_span)
    }[span_207](start_span)[span_207](end_span)

    const title = searchResults[0].title;[span_208](start_span)[span_208](end_span)
    const summaryUrl = `https://en.wikipedia.org/api/rest_v1/page/summary/${encodeURIComponent(title)}`;[span_209](start_span)[span_209](end_span)
    const summaryResponse = await limitedGet(wikipediaQueue, summaryUrl);[span_210](start_span)[span_210](end_span)
    const pageData = summaryResponse.data;[span_211](start_span)[span_211](end_span)

    if (pageData.type === 'disambiguation') {[span_212](start_span)[span_212](end_span)
      return null;[span_213](start_span)[span_213](end_span)
    }[span_214](start_span)[span_214](end_span)

    const result = {[span_215](start_span)[span_215](end_span)
      title,[span_216](start_span)[span_216](end_span)
      summary: pageData.extract || 'Summary not available.',[span_217](start_span)[span_217](end_span)
      pdfUrl: `https://en.wikipedia.org/api/rest_v1/page/pdf/${encodeURIComponent(title)}`[span_218](start_span)[span_218](end_span)
    };[span_219](start_span)[span_219](end_span)

    wikipediaCache.set(cacheKey, result);[span_220](start_span)[span_220](end_span)
    return result;[span_221](start_span)[span_221](end_span)
  });[span_222](start_span)[span_222](end_span)
}[span_223](start_span)[span_223](end_span)

async function getArxivResults(query) {[span_224](start_span)[span_224](end_span)
  const normalized = normalizeQuery(query);[span_225](start_span)[span_225](end_span)
  const cacheKey = `arxiv:${normalized}`;[span_226](start_span)[span_226](end_span)
  const cached = arxivCache.get(cacheKey);[span_227](start_span)[span_227](end_span)

  if (cached) {[span_228](start_span)[span_228](end_span)
    return cached;[span_229](start_span)[span_229](end_span)
  }[span_230](start_span)[span_230](end_span)

  return runShared(cacheKey, async () => {[span_231](start_span)[span_231](end_span)
    const cachedAfterWait = arxivCache.get(cacheKey);[span_232](start_span)[span_232](end_span)
    if (cachedAfterWait) {[span_233](start_span)[span_233](end_span)
      return cachedAfterWait;[span_234](start_span)[span_234](end_span)
    }[span_235](start_span)[span_235](end_span)

    const searchUrl = new URL('https://export.arxiv.org/api/query');[span_236](start_span)[span_236](end_span)
    searchUrl.searchParams.set('search_query', `all:${normalized}`);[span_237](start_span)[span_237](end_span)
    searchUrl.searchParams.set('start', '0');[span_238](start_span)[span_238](end_span)
    searchUrl.searchParams.set('max_results', '3');[span_239](start_span)[span_239](end_span)
    searchUrl.searchParams.set('sortBy', 'relevance');[span_240](start_span)[span_240](end_span)
    searchUrl.searchParams.set('sortOrder', 'descending');[span_241](start_span)[span_241](end_span)

    const response = await limitedGet(arxivQueue, searchUrl.toString(), { responseType: 'text' });[span_242](start_span)[span_242](end_span)
    const xml = String(response.data);[span_243](start_span)[span_243](end_span)
    const entries = xml.match(/<entry>[\s\S]*?<\/entry>/g) || [];[span_244](start_span)[span_244](end_span)
    const results = [];[span_245](start_span)[span_245](end_span)

    for (const entry of entries) {[span_246](start_span)[span_246](end_span)
      const title = decodeXml(getXmlTagValue(entry, 'title')).replace(/\s+/g, ' ').trim();[span_247](start_span)[span_247](end_span)
      const abstractUrl = decodeXml(getXmlTagValue(entry, 'id')).trim();[span_248](start_span)[span_248](end_span)
      const authors = [...entry.matchAll(/<author>[\s\S]*?<name>([\s\S]*?)<\/name>[\s\S]*?<\/author>/g)][span_249](start_span)[span_249](end_span)
        .map((match) => decodeXml(match[1]).trim())[span_250](start_span)[span_250](end_span)
        .filter(Boolean);[span_251](start_span)[span_251](end_span)

      if (!title || !abstractUrl) {[span_252](start_span)[span_252](end_span)
        continue;[span_253](start_span)[span_253](end_span)
      }[span_254](start_span)[span_254](end_span)

      const arxivId = abstractUrl.split('/ab
